name: driver_durub
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.3.0
  sizer: ^2.0.15
  image_picker: ^1.1.2
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/  # Correctly formatted assets section
